### ISSUE TITLE
Node fails to join

### ISSUE THREAD

**Issue by rajibhossen** [converged-computing/kubescaler#17]
**Describe the bug**
Resource handler returned message: "[Issue(Code=NodeCreationFailure, Message=Instances failed to join the kubernetes cluster, ResourceIds=[i-04b80822945ab1727, i-06145e8f375e3b501, i-08f235094b0381923, i-0b9f48b3839d9ad34])] (Service: null, Status Code: 0, Request ID: null)" (RequestToken: 6d549180-af57-b3a7-098b-f1b340e02f12, HandlerErrorCode: GeneralServiceException)

**To Reproduce**
`eksctl create cluster -f eks-efa-cluster-config-hpc7g.yaml`
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hossen1-cluster-4
  region: us-east-1
  version: "1.27"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        - "ec2:DescribeLaunchTemplateVersions"
        Resource: '*'

availabilityZones: ["us-east-1a", "us-east-1b"]
managedNodeGroups:
  - name: hossen1-cluster-4
    availabilityZones: ["us-east-1a"]
    instanceType: hpc7g.16xlarge
    minSize: 4
    maxSize: 8
    desiredCapacity: 4
    efaEnabled: true
    placement:
      groupName: eks-efa-testing
    labels: { "flux-operator": "true" }
    tags:
      kubernetes.io/cluster/hossen1-cluster-4: "owned"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/scaling-study-efa: "owned"
      Name: 'hossen1-cluster-4'
    propagateASGTags: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub

```

**Expected behavior**

**Version of eksctl**
0.149.0-dev+2adbe411.2023-09-11T16:14:07Z

Anything else?
